### PR TITLE
Remove invitations for deleted teams

### LINKED ISSUE #923: Invitations left for deleted teams
### Current Behavior

If you delete a team that has an outstanding invitation the invitation is left in the database.

This causes a 500 error when the admin lists invites and when the invited user logs in

```
[2022-08-26T10:06:23.818Z] ERROR: Cannot read properties of null (reading 'get') {"reqId":"req-1b","req":{"method":"GET","url":"/api/v1/user/invitations","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":52748},"res":{"statusCode":500}}
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of null (reading 'get')",
      "stack":
          TypeError: Cannot read properties of null (reading 'get')
              at Object.teamSummary (/opt/share/projects/flowforge/flowforge-dev-env/packages/flowforge/forge/db/views/Team.js:19:24)
              at /opt/share/projects/flowforge/flowforge-dev-env/packages/flowforge/forge/db/views/Invitation.js:10:41
              at Array.map (<anonymous>)
              at Object.invitationList (/opt/share/projects/flowforge/flowforge-dev-env/packages/flowforge/forge/db/views/Invitation.js:3:28)
              at Object.<anonymous> (/opt/share/projects/flowforge/flowforge-dev-env/packages/flowforge/forge/routes/api/userInvitations.js:14:48)
```

### Expected Behavior

Invites for deleted teams should be removed

### Steps To Reproduce

- Create a team
- Invite a user
- Delete the team
- Log in as invited user

### Environment

- FlowForge version: 0.8
- Node.js version: 16.x
- npm version: 8.x
- Platform/OS: Linux
- Browser: Chrome

### PR DESCRIPTION
**Pull request by hardillb**
Removes all invited will null teamId

The Invitation.teamId is set to null by a cascade rule when the team is deleted. I also did it this way because it will clean up any old orphaned Invitations from before this was added.

We should also probably delete expired invites at some point.

fixes #923

### CODE REVIEW

**Comment by knolleary** [comment]
> The Invitation.teamId is set to null by a cascade rule

Should we look at a migration that modifies the cascade policy to delete rather than set null?

**Comment by hardillb** [comment]
I think the setting to null happens because of this relationship:

https://github.com/flowforge/flowforge/blob/90ef0a19b3eb7e2ed3b12a3ff386b428eb8fb58a/forge/db/models/Team.js#L43
https://github.com/flowforge/flowforge/blob/90ef0a19b3eb7e2ed3b12a3ff386b428eb8fb58a/forge/db/models/Invitation.js#L38

Not sure how to change that to a delete.

We could move the clean up to the `beforeDestory` (I did it that way first then changed my mind) and explicitly delete the Invitations with the matching id, but I did it this way to clean up the old ones.

File: test/unit/forge/routes/api/team_spec.js [hunk 1]
```diff
@@ -1,12 +1,32 @@
...
+
+        await TestObjects.BTeam.addUser(TestObjects.alice, { through: { role: Roles.Owner } })
+
+        TestObjects.tokens = {}
+        await login('alice', 'aaPassword')
+        await login('bob', 'bbPassword')
+        await login('chris', 'ccPassword')
+    })
+
+
```
Comment (hardillb) [inline test/unit/forge/routes/api/team_spec.js:29]:
```suggestion
```

File: test/unit/forge/routes/api/team_spec.js [hunk 2]
```diff
@@ -54,6 +74,43 @@ describe('Team API', function () {
...
+                deleteResult.statusCode.should.equal(200)
+                const inviteListChris = (await app.inject({
+                    method: 'GET',
+                    url: '/api/v1/user/invitations',
+                    cookies: { sid: TestObjects.tokens.chris }
+                })).json()
+                inviteListChris.should.have.property('count', 0)
+            })
+        })
+
```
Comment (hardillb) [inline test/unit/forge/routes/api/team_spec.js:113]:
```suggestion

```

**Comment by hardillb** [comment]
Rebased on head to try and work out why tests failed

File: test/unit/forge/routes/api/team_spec.js [hunk 3]
```diff
@@ -126,4 +144,58 @@ describe('Team API', function () {
...
+        // POST /api/v1/teams
+        // - Admin/Owner/Member
+    })
+
+    describe('Delete team', async function () {
+        // DELETE /api/v1/teams/:teamId
+        // - Admin/Owner/Member
+        // - should fail if team owns projects
+
+        it('', async function () {
```
Comment (knolleary) [inline test/unit/forge/routes/api/team_spec.js:158]:
```suggestion
        it('removes pending invitations', async function () {
```
