### PR TITLE
Only render side content if team available on create team page

### LINKED ISSUE #536: Unable to create a new team
### Current Behavior

Cannot create a new team with the new page, error on the page:

```
create.vue?./node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/dist/templateLoader.js??ruleSet%5B1%5D.rules%5B2%5D!./node_modules/vue-loader/dist/index.js??ruleSet%5B1%5D.rules%5B10%5D.use%5B0%5D:89 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'slug')
    at eval (create.vue?./node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/dist/templateLoader.js??ruleSet%5B1%5D.rules%5B2%5D!./node_modules/vue-loader/dist/index.js??ruleSet%5B1%5D.rules%5B10%5D.use%5B0%5D:89:32)
    at renderFnWithContext (runtime-core.esm-bundler.js:978:21)
    at renderSlot (runtime-core.esm-bundler.js:6741:55)
    at Proxy.render (SideNavigation.vue?./node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/dist/templateLoader.js??ruleSet%5B1%5D.rules%5B2%5D!./node_modules/vue-loader/dist/index.js??ruleSet%5B1%5D.rules%5B10%5D.use%5B0%5D:14:258)
    at renderComponentRoot (runtime-core.esm-bundler.js:1021:44)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5173:57)
    at ReactiveEffect.run (reactivity.esm-bundler.js:223:25)
    at setupRenderEffect (runtime-core.esm-bundler.js:5299:9)
    at mountComponent (runtime-core.esm-bundler.js:5082:9)
```

### Expected Behavior

The create team button is not disabled.

### Steps To Reproduce

Setup a clean instance try to create a new team

### Environment

- FlowForge version: main@3959fa9a375bd02857a1b9b5977fc6d17e8cb445
- Node.js version: ?
- npm version: ?
- Platform/OS: MacOs
- Browser: Chrome

### PR DESCRIPTION
**Pull request by joepavitt**
Closes #536

### CODE REVIEW

File: frontend/src/pages/account/NoTeamsUser.vue [hunk 1]
```diff
@@ -1,41 +1,31 @@
...
-        <div class="sm:max-w-xl mx-auto w-full space-y-2">
-            <div class="max-w-xs mx-auto w-full mb-4">
-                <FlowForgeLogo/>
-                <h2 class="mt-2 text-center text-3xl font-bold text-gray-900">
-                    <span>FLOW</span><span class="font-light">FORGE</span>
-                </h2>
+    <main>
+        <form class="px-4 sm:px-6 lg:px-8 mt-4 space-y-4 text-center">
+            <p class="text-gray-700 text-lg">You need to be in a team to create projects.</p>
+            <p v-if="invitationCount === 0 && !user.admin && !settings['team:create']" class="text-gray-700 text-lg mt-10 ">Ask an Admin or Team Owner to add you to a team.</p>
```
Comment (ZJvandeWeg) [inline frontend/src/pages/account/NoTeamsUser.vue:5]: I'm not a Vue expert, but is it possible to create helpers that capture logic like:

`invitationCount === 0 && !user.admin && !settings['team:create']`? That makes logic as such more reusable

Comment (joepavitt) [reply frontend/src/pages/account/NoTeamsUser.vue:5]: In theory, yes, although not sure it's appropriate here? What is a short-hand way of describing this particular set of conditions? Also, not sure we have use for this set of conditions elsewhere?

Comment (knolleary) [reply frontend/src/pages/account/NoTeamsUser.vue:5]: I don't know if Vue has a best practice around this.

There is part of me that thinks trying to avoid too much logic in the template is worthwhile - by which I mean having long compound statements if the `v-if` property as is the case here.

If all of the 'logic' is held in computed properties it means there's a standard place to look in each component for those bits of logic - rather than have them scattered around the template itself (which could lead to things being overlooked when we have to modify the logic).

**Comment by knolleary** [comment]
Testing the PR - looks good and it does address the issue. But I did hit a related item.

When a user who is not in a team clicks on the FF logo in the top left corner, you get the following error:

image


```
runtime-core.esm-bundler.js:347 Uncaught TypeError: Cannot read properties of null (reading 'slug')
    at Proxy.home (PageHeader.vue?./node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/dist/index.js??ruleSet%5B1%5D.rules%5B10%5D.use%5B0%5D:91:32)
    at onClick._cache.<computed>._cache.<computed> (PageHeader.vue?./node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/dist/templateLoader.js??ruleSet%5B1%5D.rules%5B2%5D!./node_modules/vue-loader/dist/index.js??ruleSet%5B1%5D.rules%5B10%5D.use%5B0%5D:38:59)
    at callWithErrorHandling (runtime-core.esm-bundler.js:284:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:293:21)
    at HTMLImageElement.invoker (runtime-dom.esm-bundler.js:516:90)
```

**Comment by joepavitt** [comment]
Great find Nick, will fix this as part of this PR too.

**Comment by joepavitt** [comment]
@knolleary found the same issue in Admin & User Settings - all fixed.

File: frontend/src/pages/account/NoTeamsUser.vue (hunk 1 above)
Comment (knolleary) [reply frontend/src/pages/account/NoTeamsUser.vue:5]: >  I do fear that we're going to end up with a lot of computed variables which may make readability more difficult.

I think that's the interesting point. My instinct is having lots of well named computed variables would make the template more readable - as you don't have to parse the full logic to figure out what it is doing. For example `canCreateTeam` is understandable at a glance, rather than trying parse all the conditions in the expression - and if you need to check the logic, you have one place to look up how it is defined.

But lets not hold this PR up for this ongoing discussion.

**Review by knolleary — APPROVED** [review]
