### PR TITLE
Link button to the teamApi removeteamInvitation method

### LINKED ISSUE #339: Admin Can't delete an invited user
### Current Behavior

As as admin if I view the list of users invited to the platform at `/admin/users/invitations` There is a delete icon next to the user, however this does not appear to do anything.

If I go into the team that the user was invited to eg `/team/myteam/members/invitations` and delete from there it does remove the user

### Expected Behavior

The delete button in admin should be functional

### Steps To Reproduce

Invite an email address to a team
Goto `/admin/users/invitations` and click the delete button

### Environment

- FlowForge version: 0.2.0
- Node.js version: 16.x
- npm version: 8/x
- Platform/OS: Debian
- Browser: Chrome v99

### PR DESCRIPTION
**Pull request by joepavitt**
Closes #339

### CODE REVIEW

File: frontend/src/pages/admin/Users/Invitations.vue [hunk 1]
```diff
@@ -12,54 +12,55 @@
...
+    mounted () {
         this.fetchData()
     },
     methods: {
-        async removeInvite(teamId, inviteId) {
-            // await adminApi.removeTeamInvitation(teamId, inviteId)
-            // await this.fetchData();
+        async removeInvite (teamId, inviteId) {
+            await teamApi.removeTeamInvitation(teamId, inviteId)
+            await this.fetchData()
```
Comment (knolleary) [inline frontend/src/pages/admin/Users/Invitations.vue:56]: With all the linting changes mixed in here it is quite hard to see the material changes.

I think it is just these two lines uncommented?

Comment (joepavitt) [reply frontend/src/pages/admin/Users/Invitations.vue:56]: Yes, sorry, have linting turned on with saving of the file. The changes are:
- uncommenting the `await this.fetchData()`
- using the `teamApi` instead of the `adminApi`

Comment (knolleary) [reply frontend/src/pages/admin/Users/Invitations.vue:56]: Looks good.

I propose a task is scheduled for Friday that applies the lint rules to all frontend files and a PR raised to get them applied. We need to move in one step rather than bit by bit.

**Review by knolleary — APPROVED** [review]
