### PR TITLE
Fix instance flow update dialog

### LINKED ISSUE #2200: Duplicate labels in Instance Import dialog
### Current Behavior

image

### Expected Behavior

Only say it once.

### Steps To Reproduce

1. go to Instance overview page
2. click 'Import Instance' button
3. observe the duplicate labels

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

### PR DESCRIPTION
**Pull request by knolleary**
Closes #2200

## Description

Fixes the duplicate labels in the Instance Import dialog. Whilst fixing, also spotted the dialog calls the wrong endpoint; also fixed.

For bonus points, I've added a UI test to cover this dialog and verify it passes the provided values to the API. I feel so proud of myself for figuring out a little bit more of Cypress.

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [x] Suitable unit/system level tests have been added and they pass

### CODE REVIEW

File: frontend/src/pages/instance/components/ImportInstanceComponents.vue [hunk 1]
```diff
@@ -99,15 +99,9 @@ export default {
...
-                    const creds = JSON.parse(reader.result)
-                    if (creds.$) {
-                        // Good Start
-                        this.parts.credentials = reader.result
-                        this.errors.creds = ''
-                    } else {
-                        this.parts.credentials = undefined
-                        this.errors.creds = 'Does not look like a creds file'
-                    }
+                    JSON.parse(reader.result)
```
Comment (Pezmc) [inline frontend/src/pages/instance/components/ImportInstanceComponents.vue:102]: This parse seems to be dangling. Is it just to catch it _not_ being JSON?

**Review by Pezmc — APPROVED** [review]

File: frontend/src/pages/instance/components/ImportInstanceComponents.vue (hunk 1 above)
Comment (knolleary) [reply frontend/src/pages/instance/components/ImportInstanceComponents.vue:102]: Correct. Previously the code was parsing and looking for the `$` property. That is a sensible check for it being an encrypted creds file, however users may have unencrypted files which we should allow. So I reduced it to just check its valid JSON.
