### PR TITLE
Branding updates & fix update expired password routing after success

### LINKED ISSUE #557: Rebrand: password reset page
image

 - log in as admin
 - go to Admin Settings -> Users
 - edit the current user - click expire password (as of right this moment, you'll get an error in the forge app which I'm fixing atm, but the expiry will have happened)
 - click to navigate somewhere else in the app - you'll get prompted to update your password

### PR DESCRIPTION
**Pull request by joepavitt**
Closes #557 and #559

### CODE REVIEW

File: frontend/src/components/auth/UpdateExpiredPassword.vue [hunk 1]
```diff
@@ -59,6 +58,7 @@ export default {
             userApi.changePassword(this.input.old_password, this.input.password).then(() => {
                 console.log('DONE!')
```
Comment (knolleary) [inline frontend/src/components/auth/UpdateExpiredPassword.vue:59]:
```suggestion
```
Drive-by console.log removal

**Comment by knolleary** [comment]
Tested the various flows locally - all looking good.
