### PR TITLE
Limit password length to 1024 chars

### LINKED ISSUE #921: UX Bug: Long passwords can lead to failed sign up
### Current Behavior

When signing up for FlowForge a user can create a very long password (over 1mb in length). This leads to an error for the user without specifying why the error occurred.

### Expected Behavior

When a password is too long the submit button is disabled.

### Steps To Reproduce

_No response_

### Environment

- FlowForge version: FlowForge Cloud August 2022

### PR DESCRIPTION
**Pull request by hardillb**
The fastify body parser already limits the body of any post to 1mb
this just makes sure we don't hit that with a stupidly long password.

We can bcrypt hash a 1mb payload in aproxy 102ms with nodejs so
shouldn't be a problem, but 1024 seams like an excsively long password.

fixes #921

### CODE REVIEW

File: frontend/src/components/auth/Credentials.vue [hunk 1]
```diff
@@ -53,6 +53,10 @@ export default {
                 valid = false
                 this.errors.password = 'Required field'
             }
+            if (this.input.password.length > 1024) {
+                valid = false
+                this.errors.password = 'Too long'
+            }
             if (valid) {
```
Comment (ZJvandeWeg) [inline frontend/src/components/auth/Credentials.vue:60]: We can remove all the `valid` stuff. Don't think we need it

```suggestion
            if (this.errors.username.length === 0 && this.errors.password.length === 0) {
```

**Comment by ZJvandeWeg** [comment]
@hardillb This seems fairly easy to add a unit test for, can you add it?

File: frontend/src/components/auth/Credentials.vue (hunk 1 above)
Comment (ZJvandeWeg) [reply frontend/src/components/auth/Credentials.vue:60]: I'm fine with a response like: "ZJ, stop over engineering". But felt like a better way than to do the `valid = false` stuff

**Comment by ZJvandeWeg** [comment]
Thanks for the test! ⭐
